name: Deploy Django App to EC2

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.EC2_USER }}@${{ secrets.EC2_HOST }} << 'EOF'
            cd /home/ubuntu/student_project/Student_project
            source /home/ubuntu/student_project/venv/bin/activate
            git pull origin main
            pip install -r requirements.txt
            python manage.py collectstatic --noinput
            sudo systemctl reload nginx
            fuser -k 8000/tcp || true
            nohup python manage.py runserver 127.0.0.1:8000 &
          EOF
